### ISSUE TITLE
How to alter .txt files

### ISSUE THREAD

**Issue by guipp** [fearedbliss/Diablo-II--Vanilla-Frosting#3]
Hello!

First of all let me compliment the amazing work you did with this MOD. Prefer much more playing here than any other mod,  I think its just the right way!

But still, I became too curious as to how the rates and setting are changed in the .txt files. I realized that you did this via mpq file so I  downloaded the MPQ editor and found the .txt files within. I tried to change something simple as resitences penalty trhouth the .txt in the mpq, and saved it, but nothing changes in the game. Isnt the .txt inside the mpq that alters the settings? I tried changing several things just to see haw it affected the game but still nothing happended... Am i missing something?

Please if you coult tech me i woul really aprecciate!

Once again, amazing work!

Thank you!
GPP

**Comment by fearedbliss** [comment]
Hey,
Starting with 1.07 (LOD), the text files aren't the files that the game uses to do stuff. It actually reads the .txt files, and generates a .bin file from them. These are the files that the game actually uses.

So any .txt changes you make, you will need to run them through -direct -txt and then start a game. This will generate the bin files. After that you take those bin files and repack them into the MPQ in order to easily distribute them. My mod has all of the modifications, etc in its pack so you should be able to easily take that 'data' directory, place it in d2root, make your changes to MPQ, run the game with -direct -txt, and then take the generated files and place them back into a new MPQ file (Don't use the old MPQ because the file size will continue to increase, and also you want to have a fresh vanilla base for safety reasons).

Check out PhrozenKeep for more help/info:
https://d2mods.info/forum/
